create table if not exists public.shared_menu (
 id bigint generated by default as identity primary key,
 room_code text not null, recipe_id integer not null,
 created_at timestamptz not null default now(),
 unique(room_code,recipe_id));
alter table public.shared_menu enable row level security;
grant select,insert,delete on table public.shared_menu to anon;
grant usage,select on sequence public.shared_menu_id_seq to anon;
drop policy if exists "shared_menu_select" on public.shared_menu;
drop policy if exists "shared_menu_insert" on public.shared_menu;
drop policy if exists "shared_menu_delete" on public.shared_menu;
create policy "shared_menu_select" on public.shared_menu for select to anon using(true);
create policy "shared_menu_insert" on public.shared_menu for insert to anon with check(char_length(room_code) between 4 and 12);
create policy "shared_menu_delete" on public.shared_menu for delete to anon using(true);
alter publication supabase_realtime add table public.shared_menu;